name: Simple Job

# Every time you push to the master branch
on:
  push:
    branches:
      - master

jobs:
    Hello:
        runs-on:
            ubuntu-18.04
            steps:
                - name: Hello World!
                run: echo "Hello World"
